# Generated by Django 6.0.6 on 2026-06-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
