# Generated by Django 6.0.6 on 2026-06-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_wishlistitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.TextField(default='Black,White,Blue'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.TextField(default='S,M,L,XL'),
        ),
    ]
